### ISSUE TITLE
Error in { : task 8486 failed - "use of NULL environment is defunct"

### ISSUE THREAD

**Issue by jsacerot** [chrisschuerz/SWATplusR#29]
I was running 59,000 simulations on 30 cores. Once SWATplusR finished, I got the following error:
Error in { : task 8486 failed - "use of NULL environment is defunct"

Could you please tell me what is generating the error? how can avoid it in the future and make sure I'll not lose the results of the simulations already run?

Thank you!

**Comment by chrisschuerz** [comment]
Hi,

the error is new to me. I am sorry that you lost such a large number of simulations. 
To avoid this you could save the simulations incrementally using the input argument `save_file = 'give_a_name'`. By defining the save file a folder is generated in the `project_path` containing sqlite databases. You can load the simulations then using the function `load_swat_run(save_dir = 'path/to/give_a_name')`. This way you can at least load all runs that were successful and you do not loose any of those simulations.

Best Christoph

**Comment by jsacerot** [comment]
Probably the model crashed for a given parameter combination or my PC ran out of memory. Could you please tell me how SWATplusR deal with model crashes? Does it set the output results as NA?

Thanks!

**Comment by chrisschuerz** [comment]
You have to separate two things here:

1. A SWAT run fails, due to any error in the SWAT routine (equal to any error displayed when running SWAT in the shell)
2. Some process in R crashes (this is what happened in your case)

In case 1. `SWATplusR` catches the error and generates an error report. You can find this in the model outputs with the list variable `.$error_report`. This is a tibble that provides the info which run numbers caused errors and what types of errors occured. The respective runs are then missing in the output time series.

In case 2. you get an error in the R console. Then no simulation output is returned. That is really annoying. Because it can be the case that you ran 100k simulations and already after the 2 one an error occured. Due to how `parallel` handles such things the simulations continue and the error is returned after all simulations were done. So a lot of unnecessary time wasted. If you activate incremental saving of the simulations the successful runs are not lost, but can be reloaded with `load_swat_runs()`.
