### ISSUE TITLE
Error message at line q_sim_plus

### ISSUE THREAD

**Issue by supermollusc** [chrisschuerz/SWATplusR#41]
Hello   I have tried running the code in the vignette at https://github.com/chrisschuerz/SWATplusR/blob/master/vignettes/SWATplusR.Rmd
 and it runs until I get to the line
q_sim_plus <- run_swatplus(project_path = path_plus,
                           output = define_output(file = "channel",
                                                  variable = "flo_out",
                                                  unit = 1))
I get this error message and I don't know what it's referring to:
Error: 'C:/swat_demo/swatplus_rev57_demo/time.sim' does not exist.

Can anyone help?  Thanks

**Comment by chrisschuerz** [comment]
@supermollusc Sorry very late reply. But is there a reason why you want to work with a SWAT+ revision 57 demo? I would in general recommend now to use more recent versions of SWAT+ (at least 60.5) as there were tremendous changes since then. I know that `SWATplusR` allows to use older revisions and I still provide such old demo data. This will however change with newer versions of `SWATplusR` where a downward compatibility to old SWAT+ revisions is not necessary anymore.
