### ISSUE TITLE
run_swatplus not using the print.prt file in the TxtInOut folder

### ISSUE THREAD

**Issue by mgf-unige** [chrisschuerz/SWATplusR#45]
In the print.prt file of the TxtInOut, I have set all the yearly outputs to yes. However, when I run run_swatplus, it tells me at the end of the run that the channel.yr file doesn't exist. Indeed, it is not created when running run_swatplus while if I run the swatplus.exe, it is created right away. It seems the run_swatplus is looking for the print.prt file elsewhere? The print.prt in .model_run\thread_1 is indeed different with all yearly outputs set to "n"...

I use:

```
path_txtinout <- "D:/Projects/mymodel/Scenarios/Default/TxtInOut"

par_bound <- tibble(
  "surlag.bsn | change = abschg" = c(1, 24)
)

n_sample <- 4
n_par <- ncol(par_bound)

par_iter <- randomLHS(n=n_sample, k=n_par) %>%
  as_tibble(., .name_repair = "minimal") %>%
  set_names(names(par_bound)) %>%
  map2_df(., par_bound, ~ (.x * (.y[2] - .y[1]) + .y[1]))

q_sim <- run_swatplus(
  project_path = path_txtinout,
  output = list(
    flo_out_410 = define_output(file="channel", variable="flo_out", unit=410)
  ),
  start_date = "2005-01-01",
  end_date = "2010-12-31",
  n_thread = 4,
  save_file = "run_test",
  output_interval = "y",
  return_output = TRUE,
  parameter = par_iter
)
```

**Comment by chrisschuerz** [comment]
@mgf-unige I hope I understood you correctly. You are right. `run_swatplus` does not use the definitions for the outputs that you set in the original TxtInOut folder. The outputs are defined in the thread folders based on what you set as the `output_interval` and based on the output variables that you defined with `define_output`. So if you would set e.g. `define_output(file="channel", variable="flo_out", unit=410)` and `output_interval = "y"` the only output in the `print.prt` file the should be set to `y` in the thread folder should be `channel_yr`. I think the actual issue is here that there was a change with one of the older SWAT+ revisions and the normal channel outputs are not used anymore. You have to use **channel_sd** instead. Just check if that is already the solution to your issue.

**Comment by mgf-unige** [comment]
It indeed works! Thanks for the clarification!

**Comment by chrisschuerz** [comment]
Great! You are welcome ☺️
