### ISSUE TITLE
time.sim file missing

### ISSUE THREAD

**Issue by pekr01** [chrisschuerz/SWATplusR#52]
Dear Christoph,

I tried to run my SWAT + project with your package, but I got an error message that 'project // time.sim' does not exist in the current working directory, despite that the file is in this directory.

The demo project works well, so there's probably something different in my project.
Do you have any idea?

Petr

**Comment by chrisschuerz** [comment]
@pekr01 one thing I can think of is that you probably used blanks in your project folder name? This could cause issues with file paths. Otherwise this would be odd that it can find the same file in the demo project while it cannot find it in your own project.

**Comment by pekr01** [comment]
@chrisschuerz  Thank you for answer. No, the folder name is not a problem. It's a really weird thing. Perhaps there's a link to my project file https://uvgz-my.sharepoint.com/:f:/g/personal/krpec_p_czechglobe_cz/EkWYF90NERxCvgi-LGQcQd8BMxit-ux40Q45XUZyogxbtg?e=kljQFf

It is of course still possible that problem is somewhere between chair and computer :D

**Comment by chrisschuerz** [comment]
I will look into the project. Hope I can find something. Yes unfortunatly the latter error you describe is present far too often. This is definitely true for myself and my computer :)

**Comment by chrisschuerz** [comment]
Hi I just had a look into your project. Btw. is this really still a rev57 project (at least thats what the executable in your folder says)? The input files however say that they were generated with Editor version 2.0.1, so actually pretty recent. I would not have been sure about fully guaranteing `SWATplusR` runs smoothly with such an old revision anyways. I tried a few different executables and rev60.5.2 failed what surprised me as it comes with the SWAT+Editor version 2.0.1. A rev60.5 that I still had somewhere worked. With this I am then also able to run the project from `R`. So at least on my machine it seems that the issue is to have the correct SWAT executable for your project and is not directly related to `SWATplusR`. I hope this answer helps you at least a bit :)

**Comment by pekr01** [comment]
Hi, thank you for trying to find a solution. Yes, I tried the old revision despite that the project was set up with the latest version of the editor. Could you please share the rev60.5 file? Older revisions seem to be only available somehow packed in older swat editors.

**Comment by chrisschuerz** [comment]
Sure. You can find the revision that worked for me here: https://nc.ufz.de/s/B7Ct2XmBYieSeN7 (password: wbNBqXQb ). Please be aware, however, that the simulation of the hydrology could be different with this revision, as at the moment parts of the code are still under development. But just give it a try with the rev60.5 and see if it works for you.
