### ISSUE TITLE
Error: no such table: date

### ISSUE THREAD

**Issue by MOG91** [chrisschuerz/SWATplusR#56]
Hi Chris,

When I use save_file and save_path in run_swat2012 in version 0.5.3, I get the error "Error: no such table: date". Otherwise, I don't have any issues.

**Comment by chrisschuerz** [comment]
Yes I am sorry for that. The save load functions likely fail to work with version 0.5.3. The reason is that in the last commits I updated the reading of the dates from the simulation results. I did not update the saving and loading to and from sqlite yet. I hope I find time to fix that the next two weeks.

**Comment by MOG91** [comment]
Thank you for your reply and keep updating this amazing package.

**Comment by chrisschuerz** [comment]
Sorry that it took much longer than expected. But working with SQLite databases to incrementally save and load simulations is working again. To test it please update `SWATplusR` to version 0.6
