### ISSUE TITLE
Error with some output of "rch"

### ISSUE THREAD

**Issue by rafaelnavas** [chrisschuerz/SWATplusR#9]
Dear Chris,

I'm trying to obtain "TOT N" (total nitrogen in surface runoff) and "TOT P" (total phosphorous in surface runoff) from output/file "rch".

I test with my SWAT2012 model and your demo. Both projects deliver the next error message:

swat_dir = "C:/swat2012_rev622_demo/"
qsim = run_swat2012(project_path = swat_dir,
                    start_date = "2005-01-01",
                    end_date = "2008-12-31",
                    years_skip = 1,
                    output = define_output(file = "rch",
                                           variable = "TOT Pkg",
                                           unit = 1:3)
                    )

Building 1 thread in 'C:/swat2012_rev622_demo//.model_run': 
 Completed 1 thread in 10S                                                  
Performing 1 simulation on 1 cores: 
 Simulation 1 of 1   Time elapsed: 11S   Time remaining: 0S    Error in { : task 1 failed - "<text>:1:96: unexpected symbol
1: table %>% dplyr::filter(.[[2]] == 1) %>% dplyr::filter(filter_mon(MON)) %>% dplyr::select( TOT P
                                                                                                   ^"

Also, I tried "TOT P", "TOT N" with the same error.

Rafael

**Comment by chrisschuerz** [comment]
Hi Rafael,

to avoid blanks I implemented the variable names in a way that you have to replace blanks by underscores. So in your case the variables should be: "TOT_N" and "TOT_P". I hope that this is still working, as I had to update the routines for reading the parameter names, due to other issues. So please try that and keep me posted if it does not work.

Cheers, Christoph

**Comment by rafaelnavas** [comment]
It works
Thank you,
